#!/bin/zsh

export PORT=8080
export DB_HOST=localhost
export DB_PORT=5432
export DB_NAME=datasport-scraper
export DB_USER=user
export DB_PASSWORD=password
export ENVIRONMENT=development

python main.py
