name: Scraper build and deploy to production

on:
  push:
    branches:
      - main
    paths:
      - scraper/**
      - db/**
      - .github/workflows/scraper-build-and-deploy-prod.yaml

env:
  JOB_NAME: datasport-scraper-scraper
  IMAGE_TAG: gcr.io/${{ SECRETS.GCP_PROJECT_ID }}/datasport-scraper-scraper:latest

jobs:
  build-and-deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # project_id: ${{ SECRETS.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ SECRETS.WIF_PROVIDER }}
          service_account: ${{ SECRETS.SERVICE_ACCOUNT}}
          token_format: access_token

      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: gcr.io

      - name: Build image
        run: docker build -f scraper/Dockerfile -t ${{ env.IMAGE_TAG }} .

      - name: Push image
        run: docker push ${{ env.IMAGE_TAG }}

      - name: Update Cloud Run job image
        run: gcloud run jobs update ${{ env.JOB_NAME }} --image ${{ env.IMAGE_TAG }} --region europe-central2
